config/routes.rb
Rails.application.routes.draw do
  get "canvas", to: "static_pages#canvas"

  get "sign-up", to: "users#new"
  post "sign-up", to: "users#create"
  get "sign-in", to: "sessions#new"
  post "sign-in", to: "sessions#create"
  delete "sign-out", to: "sessions#destroy"

  get "assignments", to: "assignments#index"
  post "assignments", to: "assignments#create"
  get "assignments/:id", to: "assignments#show", as: :assignment
  get "assignments/:id/summary", to: "assignments#summary", as: :assignment_summary
  get "questions/:id", to: "assignment_questions#show", as: :question
  get "questions/:question_id/answer", to: "answers#show", as: :question_answer
  post "questions/:question_id/answer", to: "answers#create"

  resource :profile, only: [ :show, :update ]

  resource :calendar, only: [ :show ] do
    get ":date/assignments", to: "assignments#index", as: :daily_assignments
  end

  namespace :overseer do
    resources :questions, except: [ :show, :destroy ]
    resources :question_images, only: [ :index ]
    resources :question_scripts, only: [ :index ]
    resources :users, only: [ :index ]
    resources :topics, only: [ :index, :new, :create ]

    root to: "questions#index", as: :root
  end

  get "up" => "rails/health#show", as: :rails_health_check

  root "static_pages#landingpage"
end

app/models/assignment_question.rb
class AssignmentQuestion < ApplicationRecord
  belongs_to :assignment
  belongs_to :question
  has_one :user_answer, dependent: :destroy
end

app/controllers/assignment_questions_controller.rb
class AssignmentQuestionsController < AuthenticatedController
  layout "modal"

  def show
    @assignment_question = AssignmentQuestion.joins(:assignment).where(assignments: { user: current_user }).find params[:id]
    @assignment = @assignment_question.assignment
    @question = @assignment_question.question
    @answer = @question.assignment_questions.find_by!(assignment_id: @assignment.id).user_answer
    @next_assignment_question = @assignment.next_assignment_question

    @numeric_answer =
      if @question.possible_answers.any?
        false
      else
        @question.answer.match?(/\A[+-]?\d+\z/)
      end
  end
end

app/views/assignment_questions/show.html.erb
<% content_for :header_middle do %>
  <div class="relative grow overflow-hidden rounded-full bg-gray-200 max-w-lg mx-auto">
    <div class="h-2 rounded-full bg-indigo-600" style="width: <%= @assignment.answered_questions.count.to_f / @assignment.questions.count * 100 %>%"></div>
  </div>
<% end %>

<div class="h-full flex flex-col gap-4 items-center">
  <% if @question.attachable.present? %>
    <div class="w-full flex-1 overflow-y-auto scroll-shadows js-scroll-shadows">
      <div class="w-full max-w-xl flex flex-col mx-auto">
        <div class="mb-6 rounded-md overflow-hidden max-w-xl w-full flex justify-center">
          <% if @question.attachable_is_image? %>
            <%= image_tag @question.attachable.file %>
          <% elsif @question.attachable_is_script? %>
            <canvas />

            <script>
              <%= @question.attachable.code.html_safe %>

              execute({
                answer: <%= @question.answer.to_json.html_safe %>,
                params: <%= @question.attachable_parameters&.to_json&.html_safe || {} %>
              });
            </script>
          <% end %>
        </div>
        <div>
          <%= @question.text %>
        </div>
      </div>
    </div>
  <% elsif @question.text.size < 30 %>
    <div class="flex flex-1 justify-center items-center text-center sm:text-4xl text-2xl font-medium">
      <%= @question.text %>
    </div>
  <% else %>
    <div class="flex flex-1 justify-center items-center text-center sm:text-xl text-sm">
      <%= @question.text %>
    </div>
  <% end %>

  <% if @answer.present? %>
    <% if @answer.correct? %>
      <div class="text-center max-w-xl w-full p-4 bg-gray-50 rounded-md flex flex-col gap-4">
        <div>
          <aside class="text-gray-400 text-sm font-medium">Твоят отговор</aside>
          <div class="text-2xl font-medium text-gray-700"><%= @answer.value %></div>
        </div>
      </div>
      <div class="rounded-md bg-green-50 p-4 max-w-xl w-full flex justify-between items-center">
        <div class="flex items-center gap-2">
          <div class="shrink-0">
            <svg class="h-10 w-10 text-green-600" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
            </svg>
          </div>
          <div class="grow">
            <h3 class="font-medium text-green-600">Вярно</h3>
          </div>
        </div>
        <% if @next_assignment_question.present? %>
          <%= link_to "Следващ", question_path(@next_assignment_question), class: "bg-green-600 text-white px-4 py-2 rounded-md", autofocus: true %>
        <% end %>
      </div>
    <% else %>
      <div class="text-center max-w-xl w-full p-4 bg-gray-50 rounded-md flex flex-col gap-4">
        <div>
          <aside class="text-gray-400 text-sm font-medium">Твоят отговор</aside>
          <div class="text-2xl font-medium line-through text-gray-700"><%= @answer.value %></div>
        </div>
        <div>
          <aside class="text-gray-400 text-sm font-medium">Вернен отговор</aside>
          <div class="text-2xl font-medium text-gray-700"><%= @question.answer %></div>
        </div>
        <% if @question.explanation.present? %>
          <div>
            <aside class="text-gray-400 text-sm font-medium">Обяснение</aside>
            <div class="text-gray-700"><%= @question.explanation %></div>
          </div>
        <% end %>
      </div>
      <div class="rounded-md bg-red-50 p-4 max-w-xl w-full flex justify-between items-center">
        <div class="flex items-center gap-2">
          <div class="shrink-0">
            <svg class="h-10 w-10 text-red-600" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd" />
            </svg>
          </div>
          <div class="grow">
            <h3 class="font-medium text-red-600">Грешно</h3>
          </div>
        </div>
        <% if @next_assignment_question.present? %>
          <%= link_to "Следващ", question_path(@next_assignment_question), class: "bg-red-600 text-white px-4 py-2 rounded-md", autofocus: true %>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <div class="shrink-0 max-w-xl w-full">
      <% if @question.possible_answers.any? %>
        <div class="grid grid-cols-2 gap-4">
          <% @question.possible_answers.shuffle.each_with_index do |answer, index| %>
            <%= button_to answer.value, assignment_question_answer_path(@assignment, @question), method: :post, params: { answer: answer.value }, class: "w-full h-full py-3 px-4 cursor-pointer border border-gray-300 rounded-md shadow-sm text-md font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500", autofocus: index == 0 %>
          <% end %>
        </div>
      <% else %>
        <%= form_with url: question_answer_path(@assignment_question), method: :post, local: true, class: "space-y-6" do |f| %>
          <% if @numeric_answer %>
            <%= f.number_field :answer, class: "w-full py-3 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500", placeholder: "Въведете вашият отговор тук", autocomplete: "off", required: true, autofocus: true %>
          <% else %>
            <%= f.text_field :answer, class: "w-full py-3 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500", placeholder: "Въведете вашият отговор тук", autocomplete: "off", required: true, autofocus: true %>
          <% end %>
          <%= f.submit "Отговори", class: "w-full flex justify-center py-3 px-4 border border-transparent cursor-pointer rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

<script>
  function updateScrollableClasses() {
    const container = document.querySelector('.js-scroll-shadows');

    const { scrollTop, scrollHeight, clientHeight } = container;
    const canScroll = scrollHeight > clientHeight;

    container.classList.remove('scroll-shadows-top', 'scroll-shadows-bottom');

    if(!canScroll) return;

    if (container.scrollTop === 0) {
      container.classList.add('scroll-shadows-bottom');
    } else if (container.scrollTop < container.scrollHeight - container.clientHeight) {
      container.classList.add('scroll-shadows-bottom', 'scroll-shadows-top');
    } else {
      container.classList.add('scroll-shadows-top');
    }
  }

  window.addEventListener("load", () => {
    const container = document.querySelector('.js-scroll-shadows');

    container.addEventListener('scroll', () => updateScrollableClasses());
    window.addEventListener('resize', () => updateScrollableClasses());
    updateScrollableClasses();
  });
</script>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    const form = document.querySelector('form');
    const answerInput = document.querySelector('input[name="answer"]');

    form.addEventListener('submit', function(event) {
      const answer = answerInput.value;
      const submitButton = document.querySelector('input[type="submit"]');
      const answerButtons = document.querySelectorAll('button');
      answerButtons.forEach(button => {
        button.disabled = true;
        button.classList.add('opacity-50', 'cursor-not-allowed');
      });
      submitButton.disabled = true;
      submitButton.textContent = 'Отговори...';
      submitButton.classList.add('opacity-50', 'cursor-not-allowed');
    });
  });
</script>